// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

listener http:Listener ep0 = new (9090);

const string FIXED_GREETING = "Hello, world!";

service http:InterceptableService / on ep0 {
    public function createInterceptors() returns AssertionInterceptor => new;

    # The fixed hello-world greeting, for any signed-in caller
    #
    # + return - returns can be any of following types
    # http:Ok (the greeting)
    # http:Unauthorized (no valid signed-in token was presented)
    resource function get greeting(http:RequestContext ctx) returns Greeting|ErrorUnauthorized {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return {body: {code: 401, message: "no valid signed-in token was presented"}};
        }
        return {message: FIXED_GREETING};
    }
}

public type Greeting record {
    # the fixed hello-world greeting
    string message;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
